name: "Build iOS app unsigned debug IPA"

on:
  workflow_dispatch:

jobs:
  build_unsigned_debug:
    runs-on: macos-latest
    steps:
      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build unsigned xcarchive
        run: |
          xcodebuild \
            -scheme "I am Groot" \
            -sdk iphoneos \
            -configuration Debug \
            -destination "generic/platform=iOS" \
            -archivePath $RUNNER_TEMP/iamgroot.xcarchive \
            clean archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Create unsigned IPA
        run: |
          # Paths
          APP_PATH="$RUNNER_TEMP/iamgroot.xcarchive/Products/Applications/I am Groot.app"
          PAYLOAD_DIR="$RUNNER_TEMP/Payload"
          IPA_PATH="$RUNNER_TEMP/IamGroot-unsigned.ipa"

          # Prepare Payload
          mkdir -p "$PAYLOAD_DIR"
          cp -r "$APP_PATH" "$PAYLOAD_DIR"

          # Create unsigned ipa
          cd "$RUNNER_TEMP"
          zip -r "IamGroot-unsigned.ipa" Payload

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: IamGroot-unsigned-ipa
          path: ${{ runner.temp }}/IamGroot-unsigned.ipa
          retention-days: 3
