name: "Build iOS app unsigned debug IPA"

on:
  workflow_dispatch:

jobs:
  build_unsigned_debug:
    runs-on: macos-latest
    steps:
      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v4

      # Skip certificate and provisioning installation steps

      - name: Build unsigned archive
        run: |
          xcodebuild -scheme "I am Groot" \
            -archivePath $RUNNER_TEMP/iamgroot.xcarchive \
            -sdk iphoneos \
            -configuration Debug \
            -destination generic/platform=iOS \
            clean archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Export unsigned ipa using local ExportOptions.plist
        run: |
          xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/iamgroot.xcarchive \
            -exportOptionsPlist ./ExportOptions.plist \
            -exportPath $RUNNER_TEMP/build

      - name: Upload unsigned Debug IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned_debug_ipa
          path: ${{ runner.temp }}/build/*.ipa
          retention-days: 3
