name: "Build iOS app unsigned Debug IPA"

on:
  workflow_dispatch:

jobs:
  build_unsigned_debug:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3

      # Skip certificate and provisioning profile installation 
      # because we do not sign the build now.

      - name: build unsigned archive
        run: |
          # Disable code signing parameters for unsigned build
          xcodebuild -scheme "I am Groot" \
            -archivePath $RUNNER_TEMP/iamgroot.xcarchive \
            -sdk iphoneos \
            -configuration Debug \
            -destination generic/platform=iOS \
            clean archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: export unsigned ipa
        run: |
          xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/iamgroot.xcarchive \
            -exportPath $RUNNER_TEMP/build \
            -exportOptionsPlist <(cat <<EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>compileBitcode</key>
              <false/>
              <key>method</key>
              <string>development</string> <!-- or ad-hoc if preferred -->
              <key>signingStyle</key>
              <string>none</string> <!-- important: disables signing -->
              <key>stripSwiftSymbols</key>
              <true/>
              <key>teamID</key>
              <string></string> <!-- empty to avoid signing -->
              <key>thinning</key>
              <string>&lt;none&gt;</string>
            </dict>
            </plist>
            EOF
            )

      - name: Upload unsigned Debug ipa
        uses: actions/upload-artifact@v3
        with:
          name: unsigned_debug_ipa
          path: ${{ runner.temp }}/build/*.ipa
          retention-days: 3
